class User{
    constructor(
        id,
        name,
        dob,
        email,
        image,
        currentLocation,
        preferedLocation,
        currentSalary,
        expectedSalary,
        noticePeriod,
        about,
        skills=[],
        workExperience=[],
        certificatin=[],
        education=[],
        )
}